spring.application.name=backend
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.port=8090
server.servlet.session.timeout=2h
spring.datasource.url=jdbc:mysql://localhost:3306/smart_home
spring.datasource.username=root
spring.datasource.password=octav

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true